In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [23]:
from pathlib import Path
import os

print("Current working directory:")
print(Path.cwd())

csv_path = Path("../../dataset/raw/cuad/CUAD_v1/master_clauses.csv")

print("\nCSV path:")
print(csv_path.resolve())

print("\nExists:", csv_path.exists())

Current working directory:
i:\gradation project\mvp2\scripts\dataset

CSV path:
I:\gradation project\mvp2\dataset\raw\cuad\CUAD_v1\master_clauses.csv

Exists: True

In [24]:
df = pd.read_csv(csv_path)

In [25]:
print("Shape:", df.shape)

Shape: (510, 83)

In [26]:
df.head()

,Filename,Document Name,Document Name-Answer,Parties,Parties-Answer,Agreement Date,Agreement Date-Answer,Effective Date,Effective Date-Answer,Expiration Date,Expiration Date-Answer,Renewal Term,Renewal Term-Answer,Notice Period To Terminate Renewal,Notice Period To Terminate Renewal- Answer,Governing Law,Governing Law-Answer,Most Favored Nation,Most Favored Nation-Answer,Competitive Restriction Exception,Competitive Restriction Exception-Answer,Non-Compete,Non-Compete-Answer,Exclusivity,Exclusivity-Answer,No-Solicit Of Customers,No-Solicit Of Customers-Answer,No-Solicit Of Employees,No-Solicit Of Employees-Answer,Non-Disparagement,Non-Disparagement-Answer,Termination For Convenience,Termination For Convenience-Answer,Rofr/Rofo/Rofn,Rofr/Rofo/Rofn-Answer,Change Of Control,Change Of Control-Answer,Anti-Assignment,Anti-Assignment-Answer,Revenue/Profit Sharing,Revenue/Profit Sharing-Answer,Price Restrictions,Price Restrictions-Answer,Minimum Commitment,Minimum Commitment-Answer,Volume Restriction,Volume Restriction-Answer,Ip Ownership Assignment,Ip Ownership Assignment-Answer,Joint Ip Ownership,Joint Ip Ownership-Answer,License Grant,License Grant-Answer,Non-Transferable License,Non-Transferable License-Answer,Affiliate License-Licensor,Affiliate License-Licensor-Answer,Affiliate License-Licensee,Affiliate License-Licensee-Answer,Unlimited/All-You-Can-Eat-License,Unlimited/All-You-Can-Eat-License-Answer,Irrevocable Or Perpetual License,Irrevocable Or Perpetual License-Answer,Source Code Escrow,Source Code Escrow-Answer,Post-Termination Services,Post-Termination Services-Answer,Audit Rights,Audit Rights-Answer,Uncapped Liability,Uncapped Liability-Answer,Cap On Liability,Cap On Liability-Answer,Liquidated Damages,Liquidated Damages-Answer,Warranty Duration,Warranty Duration-Answer,Insurance,Insurance-Answer,Covenant Not To Sue,Covenant Not To Sue-Answer,Third Party Beneficiary,Third Party Beneficiary-Answer
0,CybergyHoldingsInc_20140520_10-Q_EX-10.27_8605784_EX-10.27_Affiliate Agreement.pdf,['MARKETING AFFILIATE AGREEMENT'],MARKETING AFFILIATE AGREEMENT,"['BIRCH FIRST GLOBAL INVESTMENTS INC.', 'MA', 'Marketing Affiliate', 'MOUNT KNOWLEDGE HOLDINGS INC.', 'Company']","Birch First Global Investments Inc. (""Company""); Mount Kowledge Holdings Inc. (""Marketing Affiliate"", ""MA"")","['8th day of May 2014', 'May 8, 2014']",5/8/14,['This agreement shall begin upon the date of its execution by MA and acceptance in writing by Company'],NaN,['This agreement shall begin upon the date of its execution by MA and acceptance in writing by Company and shall remain in effect until the end of the current calendar year and shall be automatica...,12/31/14,['This agreement shall begin upon the date of its execution by MA and acceptance in writing by Company and shall remain in effect until the end of the current calendar year and shall be automatica...,successive 1 year,['This Agreement may be terminated by either party at the expiration of its term or any renewal term upon thirty (30) days written notice to the other party.'],30 days,"['This Agreement is accepted by Company in the State of Nevada and shall be governed by and construed in accordance with the laws thereof, which laws shall prevail in the event of any conflict.']",Nevada,[],No,[],No,[],No,[],No,[],No,[],No,"['Company shall not specify the business practices of MA, nor regulate the manner in which MA shall operate its business, provided that MA (a) conducts business in a manner that reflects favorably...",Yes,[],No,[],No,[],No,"['MA may not assign, sell, lease or otherwise transfer in whole or in party any of the rights granted pursuant to this Agreement without prior written approval of Company.']",Yes,[],No,[],No,['INITIAL ORDER COMMITMENT - MA commits to purchase a minimum of 100 Units in aggregate within the Territory within the first six months of term of this Agreement.'],Yes,[],No,[],No,[],No,"['Company hereby grants MA, during the term of this Agreement, the right to use Company and/or Company trade names, trademarks or service marks on Technology or in advertising or promotion relatin...",Yes,[],No,[],No,[],No,[],No,[],No,[],No,[],No,"['MA shall keep accurate records of the sales of the Technology and Maintenance, including Client Registration Cards and shall make these records available for review by a representative of Compan...",Yes,[],No,"['The foregoing states the entire liability of Company with respect to infringement of intellectual property rights.', ""Company's liability shall not exceed the fees that MA has paid under this Ag...",Yes,[],No,"[""COMPANY'S SOLE AND EXCLUSIVE LIABILITY FOR THE WARRANTY PROVIDED IN SUBPARAGRAH (A) HEREOF SHALL BE TO CORRECT THE TECHNOLOGY TO OPERATE IN SUBSTANTIAL ACCORDANCE WITH ITS THEN CURRENT SPECIFICA...",Yes,[],No,[],No,[],No
1,EuromediaHoldingsCorp_20070215_10SB12G_EX-10.B(01)_525118_EX-10.B(01)_Content License Agreement.pdf,['VIDEO-ON-DEMAND CONTENT LICENSE AGREEMENT'],VIDEO-ON-DEMAND CONTENT LICENSE AGREEMENT,"['EuroMedia Holdings Corp.', 'Rogers', 'Rogers Cable Communications Inc.', 'Licensor']","Rogers Cable Communications Inc. (""Rogers""); EuroMedia Holdings Corp. (""Licensor"")","['July 11 , 2006']",7/11/06,"['July 11 , 2006']",7/11/06,"['The term of this Agreement (the ""Initial Term"") shall commence as of the Effective Date and, unless earlier terminated in accordance with this Agreement, shall terminate on June 30, 2010.']",6/30/10,"['At Rogers\' option, this Agreement shall renew for a subsequent term of two (2) years on the terms and conditions herein (the ""Renewal Term"").']",2 years,"[""Notwithstanding the foregoing, if, at the expiry of this Agreement following the Initial Term or the Renewal Term (if any), as applicable, Licensor and Rogers have not executed a new agreement g...",60 days,"['This Agreement is subject to all laws, regulations, license conditions and decisions of the Canadian Radio-television and Telecommunications Commission (""CRTC"") municipal, provincial and federal...","Ontario, Canada","['In the event that Licensor grants to another VOD or Pay-Per-View (""PPV"") service provider in the U.S. or the Territory the right to distribute or exhibit any Licensed Program on an earlier avail...",Yes,[],No,[],No,[],No,[],No,[],No,[],No,"[""Notwithstanding any other provision of this Agreement, Rogers may terminate this Agreement, at any time, upon sixty (60) days' prior written notice to Licensor.""]",Yes,[],No,[],No,"['This Agreement may not be assigned, sold or transferred without the prior written consent of the other party.', 'Notwithstanding the foregoing, Rogers may, without consent, assign its rights and...",Yes,"['For so long as Rogers is required by Applicable Law to pay copyright royalties relating to Licensed Programs hereunder, Licensor shall reimburse Rogers for 50% of any such royalties actually pai...",Yes,[],No,"['Licensor shall make available to Rogers, on a free trial basis and at no cost to Rogers, not less than ten (10) Licensed Programs at all times during the Term (each, a ""Promotional Program"") for...",Yes,[],No,[],No,[],No,"['During the Term, Rogers shall have the non-exclusive right to distribute and exhibit each Licensed Program on a VOD basis for a period of ninety (90) consecutive days, or such longer period as m...",Yes,[],No,[],No,[],No,['Multiple viewings of the Licensed Program shall be permitted during the Viewing Period for no additional fee and all such viewings shall be considered a single exhibition of the Licensed Program...,Yes,[],No,[],No,[],No,"[""During the Term, and for a period of twelve (12) months thereafter, Rogers (and its representatives) shall have the right, upon reasonable prior written notice to Licensor, and during regular bu...",Yes,"['Except with respect to any claim or liability arising from an infringement of any third party intellectual property right, in no event shall either party be liable for any special, indirect, con...",Yes,"['Except with respect to any claim or liability arising from an infringement of any third party intellectual property right, in no event shall either party be liable for any special, indirect, con...",Yes,[],No,[],No,[],No,[],No,[],No
2,FulucaiProductionsLtd_20131223_10-Q_EX-10.9_8368347_EX-10.9_Content License Agreement.pdf,['CONTENT DISTRIBUTION AND LICENSE AGREEMENT'],CONTENT DISTRIBUTION AND LICENSE AGREEMENT,"['Producer', 'Fulucai Productions Ltd.', 'ConvergTV', 'CONVERGTV, INC.']","CONVERGTV, INC. (“ConvergTV”); Fulucai Productions Ltd. (""Producer"")","['November 15, 2012']",11/15/12,"['November 15, 2012']",11/15/12,[],NaN,"['License Term Perpetual, unlimited runs x Other: 2 years Commencing: November 15, 2012']","perpetual, 11/15/2014",[],NaN,"['All questions with respect to the construction of this Agreement, and the rights and liabilities of the Parties hereto, shall be governed by the laws of the State of Florida.']",Florida,[],No,[],No,[],No,"['During the License Term (which is identified in the Deal Terms), Producer agrees that ConvergTV has the exclusive right to exercise the rights granted to it under this Agreement with respect to ...",Yes,[],No,[],No,[],No,[],No,[],No,[],No,[],No,"['Revenue Share as specified in this CONTENT DISTRIBUTION AND LICENSE AGREEMENT.', 'The revenue share for the Program is stated in Exhibit B.']",Yes,[],No,[],No,[],No,[],No,[],No,"['Producer further grants to ConvergTV the right and license to Distribute and re-Distribute, including relicensing or sublicensing, the Program at such dates and times as are determined by Conver...",Yes,[],No,[],No,"['Producer further grants to ConvergTV the right and license to Distribute the Program on any ConvergTV channel, and/or other distribution outlets, that exists today or that is created or develope...",Yes,"['License Term Perpetual, unlimited runs x Other: 2 years Commencing: November 15, 2012', 'Producer further grants to ConvergTV the right and license to Distribute the Program on any ConvergTV cha...",Yes,[],No,[],No,[],No,"[""Each of the Parties may, at its own expense, audit the other Party's compliance with this Agreement, including but not limited to, auditing the other Party's representations and warranties.""]",Yes,[],No,[],No,[],No,[],No,[],No,[],No,[],No
3,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf,['WEBSITE CONTENT LICENSE AGREEMENT'],WEBSITE CONTENT LICENSE AGREEMENT,"['PSiTech Corporation', 'Licensor', 'Licensee', 'Empirical Ventures, Inc.']","PSiTech Corporation (""Licensor""); Empirical Ventures, Inc (""Licensee"")","['Feb 10, 2014']",2/10/14,"['Feb 10, 2014']",2/10/14,"['The initial term of this Agreement commences as of the Effective Date and, unless terminated earlier pursuant to any express provision of this Agreement, shall continue until five (5) years foll...",2/10/19,"['Thereafter, this Agreement shall renew automatically for one (1) additional three (3) year period (the ""Renewal Term"" and collectively, together with the Initial Term, the ""Term"") unless either ...",3 years,"['Thereafter, this Agreement shall renew automatically for one (1) additional three (3) year period (the ""Renewal Term"" and collectively, together with the Initial Term, the ""Term"") unless either ...",90 days,['This Agreement shall be governed by and construed in accordance with the internal laws of the State of Nevada without giving effect to any choice or conflict of law provision or rule.'],Nevada,[],No,[],No,[],No,"[""Subject to Licensee's on\xadgoing compliance with Section 3.2 and all other terms and conditions of this Agreement, Licensor grants to Licensee an exclusive (save for rights reserved to Licensor...",Yes,[],No,[],No,[],No,[],No,[],No,"[""For purposes of the preceding sentence, and without limiting its generality, any merger, consolidation or reorganization involving Licensee (regardless of whether Licensee is a surviving or disa...",Yes,"['Any purported assignment, delegation or transfer in violation of this Section 11.7 is void from the outset and shall be of no force or effect.', ""Licensee shall not assign or otherwise transfer ...",Yes,"['In addition to the License Fee payable in accordance with Section 5.1, Licensee shall pay a royalty (""Royalty"") to Licensor according to the following schedule (""Royalty Schedule""): Subscriber...",Yes,[],No,[],No,[],No,[],No,[],No,"[""Subject to Licensee's on\xadgoing compliance with Section 3.2 and all other terms and conditions of this Agreement, Licensor grants to Licensee an exclusive (save for rights reserved to Licensor...",Yes,"[""Subject to Licensee's on\xadgoing compliance with Section 3.2 and all other terms and conditions of this Agreement, Licensor grants to Licensee an exclusive (save for rights reserved to Licensor...",Yes,[],No,[],No,[],No,[],No,[],No,[],No,"['Licensor will pay the cost of such audits unless an audit reveals a discrepancy in payment or reporting of five percent (5%) or more, in which case the Licensee shall reimburse the Licensor for ...",Yes,"[""The provisions of Section 9.1 and Section 9.2 will not apply to limit the Licensee's indemnification obligations under Section 8.2, or in the case of Licensee's gross negligence or wilful miscon...",Yes,"['NEITHER PARTY SHALL BE LIABLE UNDER OR IN CONNECTION WITH THIS AGREEMENT FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, LIQUIDATED, SPECIAL OR EXEMPLARY DAMAGES OR PENALTIES, INCLUDING WITHOUT LIMITAT...",Yes,[],No,[],No,[],No,[],No,[],No
4,IdeanomicsInc_20160330_10-K_EX-10.26_9512211_EX-10.26_Content License Agreement.pdf,['CONTENT LICENSE AGREEMENT'],CONTENT LICENSE AGREEMENT,"['YOU ON DEMAND HOLDINGS, INC.', 'Licensor', 'Licensee', 'Beijing Sun Seven Stars Culture Development Limited']","Beijing Sun Seven Stars Culture Development Limited (""Licensor""); YOU ON DEMAND HOLDINGS, INC (""Licensee"")","['December 21, 2015']",12/21/15,"['December 21, 2015']",12/21/15,"['The Term of this Agreement (the ""Term"") shall commence on the Effective Date listed above and continue for twenty (20) years, unless sooner terminated as provided in Section 7(b) [Term and Termi...",12/21/35,[],NaN,[],NaN,"['This Agreement shall be governed by and construed in all respects in accordance with the laws of the State of New York, without giving effect to any conflicts of laws principles.']",New York,[],No,[],No,[],No,[],No,[],No,[],No,[],No,[],No,"['Should Licensee agree to be the vendor for an Additional Title, Licensor and Licensee will negotiate in good faith to mutually agree upon the pricing and terms for each Additional Title in an am...",Yes,[],No,"[""Except as otherwise specified in the previous sentence, Licensee may not sublicense any of its rights under Section 2(a) [License Grant] without Licensor's prior written consent, which shall not...",Yes,"['For content listed in Schedule A6 of Schedule A (each a ""Project""), Licensor will only grant Licensee certain profit participation rights, for certain durations, as detailed and set forth in Sch...",Yes,[],No,[],No,[],No,[],No,[],No,"['Limitations on Rights Granted: the following distribution methods are permitted: non-theatrical, public video, ship and hotel rights (all not earlier than the US theatrical release); home video ...",Yes,[],No,[],No,[],No,[],No,"['In exchange for the Share Consideration, Licensor hereby grants to Licensee a non-exclusive, royalty-free, perpetual and non-perpetual license (subject to the duration and scope, and format limi...",Yes,[],No,[],No,"['Until one (1) year after the expiration of the Profit Participation of each Project, the books and records will be available for inspection by a certified accounting firm or CPA once per year up...",Yes,"['EXCEPT FOR THE ABOVE INDEMNIFICATION OBLIGATIONS AND FOR BREACHES OF SECTION 14, NEITHER PARTY SHALL BE LIABLE TO THE OTHER FOR ANY INCIDENTAL, CONSEQUENTIAL, SPECIAL OR PUNITIVE DAMAGES ARISING...",Yes,"['EXCEPT FOR THE ABOVE INDEMNIFICATION OBLIGATIONS AND FOR BREACHES OF SECTION 14, NEITHER PARTY SHALL BE LIABLE TO THE OTHER FOR ANY INCIDENTAL, CONSEQUENTIAL, SPECIAL OR PUNITIVE DAMAGES ARISING...",Yes,[],No,[],No,[],No,[],No,[],No

In [27]:
for i, col in enumerate(df.columns):
    print(i, "→", col)

0 → Filename
1 → Document Name
2 → Document Name-Answer
3 → Parties
4 → Parties-Answer
5 → Agreement Date
6 → Agreement Date-Answer
7 → Effective Date
8 → Effective Date-Answer
9 → Expiration Date
10 → Expiration Date-Answer
11 → Renewal Term
12 → Renewal Term-Answer
13 → Notice Period To Terminate Renewal
14 → Notice Period To Terminate Renewal- Answer
15 → Governing Law
16 → Governing Law-Answer
17 → Most Favored Nation
18 → Most Favored Nation-Answer
19 → Competitive Restriction Exception
20 → Competitive Restriction Exception-Answer
21 → Non-Compete
22 → Non-Compete-Answer
23 → Exclusivity
24 → Exclusivity-Answer
25 → No-Solicit Of Customers
26 → No-Solicit Of Customers-Answer
27 → No-Solicit Of Employees
28 → No-Solicit Of Employees-Answer
29 → Non-Disparagement
30 → Non-Disparagement-Answer
31 → Termination For Convenience
32 → Termination For Convenience-Answer
33 → Rofr/Rofo/Rofn
34 → Rofr/Rofo/Rofn-Answer
35 → Change Of Control
36 → Change Of Control-Answer
37 → Anti-Assignment
38 → Anti-Assignment-Answer
39 → Revenue/Profit Sharing
40 → Revenue/Profit Sharing-Answer
41 → Price Restrictions
42 → Price Restrictions-Answer
43 → Minimum Commitment
44 → Minimum Commitment-Answer
45 → Volume Restriction
46 → Volume Restriction-Answer
47 → Ip Ownership Assignment
48 → Ip Ownership Assignment-Answer
49 → Joint Ip Ownership
50 → Joint Ip Ownership-Answer
51 → License Grant
52 → License Grant-Answer
53 → Non-Transferable License
54 → Non-Transferable License-Answer
55 → Affiliate License-Licensor
56 → Affiliate License-Licensor-Answer
57 → Affiliate License-Licensee
58 → Affiliate License-Licensee-Answer
59 → Unlimited/All-You-Can-Eat-License
60 → Unlimited/All-You-Can-Eat-License-Answer
61 → Irrevocable Or Perpetual License
62 → Irrevocable Or Perpetual License-Answer
63 → Source Code Escrow
64 → Source Code Escrow-Answer
65 → Post-Termination Services
66 → Post-Termination Services-Answer
67 → Audit Rights
68 → Audit Rights-Answer
69 → Uncapped Liability
70 → Uncapped Liability-Answer
71 → Cap On Liability
72 → Cap On Liability-Answer
73 → Liquidated Damages
74 → Liquidated Damages-Answer
75 → Warranty Duration
76 → Warranty Duration-Answer
77 → Insurance
78 → Insurance-Answer
79 → Covenant Not To Sue
80 → Covenant Not To Sue-Answer
81 → Third Party Beneficiary
82 → Third Party Beneficiary-Answer

In [28]:
# Categories suitable for clause classification
CLAUSE_CATEGORIES = [
    "Governing Law",
    "Most Favored Nation",
    "Non-Compete",
    "Exclusivity",
    "No-Solicit of Customers",
    "Competitive Restriction Exception",
    "No-Solicit of Employees",
    "Non-Disparagement",
    "Termination for Convenience",
    "Rofr/Rofo/Rofn",
    "Change of Control",
    "Anti-Assignment",
    "Revenue/Profit Sharing",
    "Price Restrictions",
    "Minimum Commitment",
    "Volume Restriction",
    "IP Ownership Assignment",
    "Joint IP Ownership",
    "License Grant",
    "Non-Transferable License",
    "Affiliate License-Licensor",
    "Affiliate License-Licensee",
    "Unlimited/All-You-Can-Eat-License",
    "Irrevocable or Perpetual License",
    "Source Code Escrow",
    "Post-Termination Services",
    "Audit Rights",
    "Uncapped Liability",
    "Cap on Liability",
    "Liquidated Damages",
    "Insurance",
    "Covenant Not to Sue",
    "Third Party Beneficiary",
]


# Categories that are mainly information extraction tasks
EXTRACTION_CATEGORIES = [
    "Document Name",
    "Parties",
    "Agreement Date",
    "Effective Date",
    "Expiration Date",
    "Renewal Term",
    "Notice Period To Terminate Renewal",
    "Warranty Duration",
]

In [29]:
def find_column(category, suffix=""):
    """
    Find the actual CUAD CSV column corresponding to a category.
    Handles small naming differences between CUAD versions.
    """

    target = f"{category}{suffix}".strip().lower()

    # Exact match first
    for col in df.columns:
        if str(col).strip().lower() == target:
            return col

    # Normalized comparison
    def normalize(text):
        return (
            str(text)
            .lower()
            .replace("-", "")
            .replace("_", "")
            .replace(" ", "")
        )

    normalized_target = normalize(target)

    for col in df.columns:
        if normalize(col) == normalized_target:
            return col

    return None

In [30]:
print("\n" + "=" * 70)
print("CATEGORY VERIFICATION")
print("=" * 70)

print("\nClause categories:")

missing_clause_categories = []

for category in CLAUSE_CATEGORIES:
    context_col = find_column(category)

    if context_col:
        print(f"[OK] {category:<45} -> {context_col}")
    else:
        print(f"[MISSING] {category}")
        missing_clause_categories.append(category)


print("\nExtraction categories:")

missing_extraction_categories = []

for category in EXTRACTION_CATEGORIES:
    context_col = find_column(category)
    answer_col = find_column(category, "-Answer")

    if context_col and answer_col:
        print(
            f"[OK] {category:<45} -> "
            f"{context_col} | {answer_col}"
        )
    else:
        print(
            f"[MISSING] {category} | "
            f"context={context_col} answer={answer_col}"
        )
        missing_extraction_categories.append(category)

======================================================================
CATEGORY VERIFICATION
======================================================================

Clause categories:
[OK] Governing Law                                 -> Governing Law
[OK] Most Favored Nation                           -> Most Favored Nation
[OK] Non-Compete                                   -> Non-Compete
[OK] Exclusivity                                   -> Exclusivity
[OK] No-Solicit of Customers                       -> No-Solicit Of Customers
[OK] Competitive Restriction Exception             -> Competitive Restriction Exception
[OK] No-Solicit of Employees                       -> No-Solicit Of Employees
[OK] Non-Disparagement                             -> Non-Disparagement
[OK] Termination for Convenience                   -> Termination For Convenience
[OK] Rofr/Rofo/Rofn                                -> Rofr/Rofo/Rofn
[OK] Change of Control                             -> Change Of Control
[OK] Anti-Assignment                               -> Anti-Assignment
[OK] Revenue/Profit Sharing                        -> Revenue/Profit Sharing
[OK] Price Restrictions                            -> Price Restrictions
[OK] Minimum Commitment                            -> Minimum Commitment
[OK] Volume Restriction                            -> Volume Restriction
[OK] IP Ownership Assignment                       -> Ip Ownership Assignment
[OK] Joint IP Ownership                            -> Joint Ip Ownership
[OK] License Grant                                 -> License Grant
[OK] Non-Transferable License                      -> Non-Transferable License
[OK] Affiliate License-Licensor                    -> Affiliate License-Licensor
[OK] Affiliate License-Licensee                    -> Affiliate License-Licensee
[OK] Unlimited/All-You-Can-Eat-License             -> Unlimited/All-You-Can-Eat-License
[OK] Irrevocable or Perpetual License              -> Irrevocable Or Perpetual License
[OK] Source Code Escrow                            -> Source Code Escrow
[OK] Post-Termination Services                     -> Post-Termination Services
[OK] Audit Rights                                  -> Audit Rights
[OK] Uncapped Liability                            -> Uncapped Liability
[OK] Cap on Liability                              -> Cap On Liability
[OK] Liquidated Damages                            -> Liquidated Damages
[OK] Insurance                                     -> Insurance
[OK] Covenant Not to Sue                           -> Covenant Not To Sue
[OK] Third Party Beneficiary                       -> Third Party Beneficiary

Extraction categories:
[OK] Document Name                                 -> Document Name | Document Name-Answer
[OK] Parties                                       -> Parties | Parties-Answer
[OK] Agreement Date                                -> Agreement Date | Agreement Date-Answer
[OK] Effective Date                                -> Effective Date | Effective Date-Answer
[OK] Expiration Date                               -> Expiration Date | Expiration Date-Answer
[OK] Renewal Term                                  -> Renewal Term | Renewal Term-Answer
[OK] Notice Period To Terminate Renewal            -> Notice Period To Terminate Renewal | Notice Period To Terminate Renewal- Answer
[OK] Warranty Duration                             -> Warranty Duration | Warranty Duration-Answer

In [31]:
print("\n" + "=" * 70)
print("BUILDING CLAUSE CLASSIFICATION DATASET")
print("=" * 70)

classification_rows = []

for _, row in df.iterrows():

    document_id = row["Filename"]

    for category in CLAUSE_CATEGORIES:

        context_col = find_column(category)

        if context_col is None:
            continue

        clause_text = row[context_col]

        # Ignore empty / missing clauses
        if pd.isna(clause_text):
            continue

        clause_text = str(clause_text).strip()

        if not clause_text:
            continue

        # Ignore obvious missing values
        if clause_text.lower() in {"nan", "none", "null"}:
            continue

        answer_col = find_column(category, "-Answer")

        answer = None

        if answer_col:
            value = row[answer_col]

            if pd.notna(value):
                answer = str(value).strip()

        classification_rows.append({
            "document_id": document_id,
            "clause_type": category,
            "clause_text": clause_text,
            "answer": answer,
        })


classification_df = pd.DataFrame(classification_rows)

======================================================================
BUILDING CLAUSE CLASSIFICATION DATASET
======================================================================

In [32]:
print("\n" + "=" * 70)
print("BUILDING INFORMATION EXTRACTION DATASET")
print("=" * 70)

extraction_rows = []

for _, row in df.iterrows():

    document_id = row["Filename"]

    for category in EXTRACTION_CATEGORIES:

        context_col = find_column(category)
        answer_col = find_column(category, "-Answer")

        if context_col is None or answer_col is None:
            continue

        context = row[context_col]
        answer = row[answer_col]

        # We need an actual labeled example
        if pd.isna(context) and pd.isna(answer):
            continue

        context = "" if pd.isna(context) else str(context).strip()
        answer = "" if pd.isna(answer) else str(answer).strip()

        # Ignore completely empty records
        if not context and not answer:
            continue

        extraction_rows.append({
            "document_id": document_id,
            "category": category,
            "context": context,
            "answer": answer,
        })


extraction_df = pd.DataFrame(extraction_rows)

======================================================================
BUILDING INFORMATION EXTRACTION DATASET
======================================================================

In [35]:
from pathlib import Path

# Output directory
output_dir = Path("dataset/processed")
output_dir.mkdir(parents=True, exist_ok=True)

# Output paths
classification_path = output_dir / "clause_classification.csv"
extraction_path = output_dir / "information_extraction.csv"

# Save classification dataset
classification_df.to_csv(
    classification_path,
    index=False,
    encoding="utf-8-sig"
)

# Save extraction dataset
extraction_df.to_csv(
    extraction_path,
    index=False,
    encoding="utf-8-sig"
)

print("Saved successfully!")
print(f"Classification: {classification_path}")
print(f"Extraction:     {extraction_path}")

Saved successfully!
Classification: dataset\processed\clause_classification.csv
Extraction:     dataset\processed\information_extraction.csv

In [36]:
print("Classification shape:", classification_df.shape)
print("Extraction shape:", extraction_df.shape)

print("\nClassification categories:")
print(classification_df["clause_type"].value_counts())

print("\nExtraction categories:")
print(extraction_df["category"].value_counts())

Classification shape: (16830, 4)
Extraction shape: (4080, 4)

Classification categories:
clause_type
Governing Law                        510
Joint IP Ownership                   510
Covenant Not to Sue                  510
Insurance                            510
Liquidated Damages                   510
Cap on Liability                     510
Uncapped Liability                   510
Audit Rights                         510
Post-Termination Services            510
Source Code Escrow                   510
Irrevocable or Perpetual License     510
Unlimited/All-You-Can-Eat-License    510
Affiliate License-Licensee           510
Affiliate License-Licensor           510
Non-Transferable License             510
License Grant                        510
IP Ownership Assignment              510
Most Favored Nation                  510
Volume Restriction                   510
Minimum Commitment                   510
Price Restrictions                   510
Revenue/Profit Sharing               510
Anti-Assignment                      510
Change of Control                    510
Rofr/Rofo/Rofn                       510
Termination for Convenience          510
Non-Disparagement                    510
No-Solicit of Employees              510
Competitive Restriction Exception    510
No-Solicit of Customers              510
Exclusivity                          510
Non-Compete                          510
Third Party Beneficiary              510
Name: count, dtype: int64

Extraction categories:
category
Document Name                         510
Parties                               510
Agreement Date                        510
Effective Date                        510
Expiration Date                       510
Renewal Term                          510
Notice Period To Terminate Renewal    510
Warranty Duration                     510
Name: count, dtype: int64

In [37]:
classification_df.groupby("clause_type").size().sort_values(ascending=False)

clause_type
Affiliate License-Licensee           510
Most Favored Nation                  510
Unlimited/All-You-Can-Eat-License    510
Uncapped Liability                   510
Third Party Beneficiary              510
Termination for Convenience          510
Source Code Escrow                   510
Rofr/Rofo/Rofn                       510
Revenue/Profit Sharing               510
Price Restrictions                   510
Post-Termination Services            510
Non-Transferable License             510
Non-Disparagement                    510
Non-Compete                          510
No-Solicit of Employees              510
No-Solicit of Customers              510
Minimum Commitment                   510
Affiliate License-Licensor           510
Liquidated Damages                   510
License Grant                        510
Joint IP Ownership                   510
Irrevocable or Perpetual License     510
Insurance                            510
IP Ownership Assignment              510
Governing Law                        510
Exclusivity                          510
Covenant Not to Sue                  510
Competitive Restriction Exception    510
Change of Control                    510
Cap on Liability                     510
Audit Rights                         510
Anti-Assignment                      510
Volume Restriction                   510
dtype: int64

In [38]:
# Check answers distribution
answer_stats = (
    classification_df
    .assign(
        has_answer=classification_df["answer"].notna()
        & classification_df["answer"].astype(str).str.strip().ne("")
    )
    .groupby("clause_type")["has_answer"]
    .agg(["count", "sum"])
)

answer_stats["missing"] = (
    answer_stats["count"] - answer_stats["sum"]
)

answer_stats

                                   count  sum  missing
clause_type
Affiliate License-Licensee           510  510        0
Affiliate License-Licensor           510  510        0
Anti-Assignment                      510  510        0
Audit Rights                         510  510        0
Cap on Liability                     510  510        0
Change of Control                    510  510        0
Competitive Restriction Exception    510  510        0
Covenant Not to Sue                  510  510        0
Exclusivity                          510  510        0
Governing Law                        510  434       76
IP Ownership Assignment              510  510        0
Insurance                            510  510        0
Irrevocable or Perpetual License     510  510        0
Joint IP Ownership                   510  510        0
License Grant                        510  510        0
Liquidated Damages                   510  510        0
Minimum Commitment                   510  510        0
Most Favored Nation                  510  510        0
No-Solicit of Customers              510  510        0
No-Solicit of Employees              510  510        0
Non-Compete                          510  510        0
Non-Disparagement                    510  510        0
Non-Transferable License             510  510        0
Post-Termination Services            510  510        0
Price Restrictions                   510  510        0
Revenue/Profit Sharing               510  510        0
Rofr/Rofo/Rofn                       510  510        0
Source Code Escrow                   510  510        0
Termination for Convenience          510  510        0
Third Party Beneficiary              510  510        0
Uncapped Liability                   510  510        0
Unlimited/All-You-Can-Eat-License    510  510        0
Volume Restriction                   510  510        0

In [39]:
classification_df[
    classification_df["clause_type"] == "Liquidated Damages"
][
    ["document_id", "clause_type", "clause_text", "answer"]
].head(10)

,document_id,clause_type,clause_text,answer
29,CybergyHoldingsInc_20140520_10-Q_EX-10.27_8605784_EX-10.27_Affiliate Agreement.pdf,Liquidated Damages,[],No
62,EuromediaHoldingsCorp_20070215_10SB12G_EX-10.B(01)_525118_EX-10.B(01)_Content License Agreement.pdf,Liquidated Damages,[],No
95,FulucaiProductionsLtd_20131223_10-Q_EX-10.9_8368347_EX-10.9_Content License Agreement.pdf,Liquidated Damages,[],No
128,GopageCorp_20140221_10-K_EX-10.1_8432966_EX-10.1_Content License Agreement.pdf,Liquidated Damages,[],No
161,IdeanomicsInc_20160330_10-K_EX-10.26_9512211_EX-10.26_Content License Agreement.pdf,Liquidated Damages,[],No
194,DeltathreeInc_19991102_S-1A_EX-10.19_6227850_EX-10.19_Co-Branding Agreement_ Service Agreement.pdf,Liquidated Damages,[],No
227,EdietsComInc_20001030_10QSB_EX-10.4_2606646_EX-10.4_Co-Branding Agreement.pdf,Liquidated Damages,[],No
260,IntegrityMediaInc_20010329_10-K405_EX-10.17_2373875_EX-10.17_Co-Branding Agreement.pdf,Liquidated Damages,[],No
293,MusclepharmCorp_20170208_10-KA_EX-10.38_9893581_EX-10.38_Co-Branding Agreement.pdf,Liquidated Damages,[],No
326,TomOnlineInc_20060501_20-F_EX-4.46_749700_EX-4.46_Co-Branding Agreement.pdf,Liquidated Damages,[],No